services:

   server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./diskshot-laravel:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=diskshotdb
      - DB_USERNAME=root
      - DB_PASSWORD=1234
    depends_on:
      - database
    restart: always

   database:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=diskshotdb
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

      
volumes:
  dbdata: